/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Lyga(props) {
  const { nodes, materials } = useGLTF("three/LYGA.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body_part_3_pivot.geometry}
        material={materials.magnifying_glass_3}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body_part_2.geometry}
        material={materials.magnifying_glass_3}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Body_part_1_pivot.geometry}
        material={materials.magnifying_glass_3}
        rotation={[0, 1.571, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Text001.geometry}
        material={materials["Material.002"]}
        position={[1.183, 0.102, -0.525]}
        rotation={[0, Math.PI / 4, 0]}
        scale={1.901}
      />
    </group>
  );
}

useGLTF.preload("three/LYGA.gltf");
// export default Lyga
