import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    screens: {
      sm: "768px",
      md: "1080px",
      lg: "1600px",
    },
    spacing: {
      "0": "0",
      1: "1px",
      2: "2px",
      "02e": "0.2em",
      "05e": "0.5em",
      "1e": "1em",
      sm: "var(--space-sm)",
      md: "var(--space-md)",
      lg: "var(--space-lg)",
      xl: "var(--space-xl)",
      200: "var(--space-200)",
      gutter: "var(--gutter)",
      "header-height": "var(--header-height)",
      "md-mobile": "var(--space-md-mobile)",
    },
    colors: {
      // bg: "var(--color-bg)",
      primary: "var(--color-primary)",
      secondary: "var(--color-secondary)",
      white: "white",
      black: "black",
      red: "#ff0000",
      gray: "var(--color-gray)",
      "gray-25": "var(--color-gray-25)",
      "gray-50": "var(--color-gray-50)",
      "gray-100": "var(--color-gray-100)",
      hover: "var(--color-hover)",
      muted: "var(--color-muted)",
      green: "var(--color-green)",
      blue: "var(--color-blue)",
    },
    fontSize: {
      // "sm--md": ["var(--text-sm--md)", "1.2"],
      // "sm--lg": ["var(--text-sm--lg)", "1.2"],
      // "sm--xl": ["var(--text-sm--xl)", "1.2"],
      sm: ["var(--text-sm)", "1.2"],
      md: ["var(--text-md)", "1.2"],
      lg: ["var(--text-lg)", "1.075"],
      xl: ["var(--text-xl)", "0.875"],
      "sm--lg": "var(--sm--text-lg)",
    },
    fontFamily: {
      sans: "var(--font-primary)",
      mono: "var(--font-mono)",
      bold: "var(--font-mono-b)",
    },
  },
  plugins: [],
};
export default config;
